server:
  port: 8088

logging:
  level:
    org.springframework: debug

spring:
  messages:
    basename: "messages"
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  security:
    user:
      name: username
      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
